server:
  port: 8009

spring:
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: localhost
      port: 27017
      database: in_techs

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

image:
  upload:
    dir: ${IMAGE:C:\Users\user\Desktop\오목눈이}
  user: ${USER_BASIC_IMAGE:}

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      bucket: ${BUCKET:}
    credentials:
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}

logging.level.com.amazonaws.util.EC2MetadataUtils: error

auth:
  jwt:
    exp:
      access: ${ACCESS_TOKEN_EXP:3600}
      refresh: ${REFRESH_TOKEN_EXP:10000}
    secret: ${SECRET_KEY:}
    header: ${HEADER:Authorization}
    prefix: ${PREFIX:Bearer}
